import { Space_Grotesk, Inter } from "next/font/google";
import { Metadata } from "next";
import Footer from "./components/Footer";
import Navbar from "./components/Navbar";
import ClientLayout from "./components/ClientLayout";

import "./globals.css";

const spaceGrotesk = Space_Grotesk({
  variable: "--font-space-grotesk",
  subsets: ["latin"],
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Foul Play FM",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${spaceGrotesk.variable} ${inter.variable} antialiased`}
      >
        <Navbar />
        {children}
        <ClientLayout />
        <Footer />
      </body>
    </html>
  );
}
